go_import_path: github.com/cloudflare/unsee

jobs:
  include:
    - stage: Test Go code
      language: go
      go:  "1.9.2"
      before_script:
        - make mock-assets
      cache:
        directories:
          - vendor
      script: make test-go

    - stage: Test JavaScript code
      language: node_js
      node_js: "8"
      env:
        - NODE_ENV=test
      cache:
        directories:
          - node_modules
      script: make test-js

    - stage: Lint Go code
      language: go
      go:  "1.9.2"
      script: make lint-go

    - stage: Lint JavaScript code
      language: node_js
      node_js: "8"
      cache:
        directories:
          - node_modules
      script: make lint-js

    - stage: Build Docker image
      sudo: true
      addons:
        apt:
          packages:
            - docker-ce
      script: make docker-image
